spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 958734250526-eokqdt3cbpsgi97qdkpjcntdiqeonfpe.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: WOvuyqNRrjkYukxK78Q4
            client-secret: OoGkmHxKcG
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 9cb577bdc1e04f73c740cd288adde0ea
            client-secret: AiUEaeDiVFKjXJIEg7UGncnFLuD93oh6
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id